

https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: '..\..\..\..\geckodriver' executable needs to be in PATH. 



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: '..\..\..\..\geckodriver' executable needs to be in PATH. 



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: '..\..\..\..\..\geckodriver' executable needs to be in PATH. 



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: '..\..\..\..\..\geckodriver' executable needs to be in PATH. 



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: '\home\yo2Ã\PYTHON\geckodriver' executable needs to be in PATH. 



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: '\home\yo2Ã\PYTHON\geckodriver' executable needs to be in PATH. 



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Unable to find a matching set of capabilities



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Unable to find a matching set of capabilities



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Unable to find a matching set of capabilities



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Unable to find a matching set of capabilities



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Unable to find a matching set of capabilities



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Unable to find a matching set of capabilities



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Failed to start browser /usr/bin/firefox: no such file or directory



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Failed to start browser /usr/bin/firefox: no such file or directory



https://www.google.com/search?q=Travelodge%20City%20CentreTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Failed to start browser /usr/bin/firefox: no such file or directory



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Failed to start browser /usr/bin/firefox: no such file or directory



https://www.google.com/search?q=KIP%20HotelTraceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 85, in parse_start_url
    yield Request(url=actual_crawl_url,cookies=self.get_cookies(actual_crawl_url),callback=self.getBookingDetails,meta={'hotelname':hotelname})
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 98, in get_cookies
    driver = webdriver.Firefox(executable_path=geckodriver, firefox_options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: connection refused



https://www.google.com/travel/hotels/entity/CgsIto769aif5OCnARAB/prices?g2lb=2502548,4258168,4260007,4270442,4274032,4291318,4305595,4306835,4308216,4314846,4317915,4326765,4328159,4329288,4330113,4339688,4341278,4344617,4347918,4354453,4270859,4284970,4291517,4316256&hl=en&gl=my&un=1&grf=EmQKLAgOEigSJnIkKiIKBwjkDxADGBcSBwjkDxADGBggADAeQMoCSgcI5A8QAhgcCjQIDBIwEi6yASsSKQonCiUweDMxY2FlYzg0MmZlNmNlMjU6MHhhN2MxOTBmYThlYmU4NzM2&rp=ELaO-vWon-TgpwEQto769aif5OCnATgCQABIAQ&ictx=1Traceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 162, in getBookingDetails
    driver.find_elements_by_xpath('//button[@class="VfPpkd-Bz112c-LgbsSe yHy1rc eT1oJ QDwDD GwzyAc cU51ne"]')[5].click()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=44675): Max retries exceeded with url: /session/f094cf7d-add6-4db3-ad2d-52b64c67db2b/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb41473ec>: Failed to establish a new connection: [Errno 111] Connection refused',))


https://www.google.com/travel/hotels/entity/CgsIto769aif5OCnARAB/prices?g2lb=2502548,4258168,4260007,4270442,4274032,4291318,4305595,4306835,4308216,4314846,4317915,4328159,4329288,4330113,4339686,4341278,4347918,4270859,4284970,4291517,4316256&hl=en&gl=my&un=1&grf=EmQKLAgOEigSJnIkKiIKBwjkDxADGBcSBwjkDxADGBggADAeQMoCSgcI5A8QAhgcCjQIDBIwEi6yASsSKQonCiUweDMxY2FlYzg0MmZlNmNlMjU6MHhhN2MxOTBmYThlYmU4NzM2&rp=ELaO-vWon-TgpwE4AkAASAE&ictx=1Traceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 103, in getBookingDetails
    driver = webdriver.Firefox(executable_path=geckodriver, options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: connection refused



https://www.google.com/travel/hotels/entity/CgsIto769aif5OCnARAB/prices?g2lb=2502548,4258168,4260007,4270442,4274032,4291318,4305595,4306835,4308216,4308226,4314846,4317915,4328159,4329288,4330113,4341278,4347918,4351597,4356223,4270859,4284970,4291517,4316256&hl=en&gl=my&un=1&grf=EmQKLAgOEigSJnIkKiIKBwjkDxADGBcSBwjkDxADGBggADAeQMoCSgcI5A8QAhgcCjQIDBIwEi6yASsSKQonCiUweDMxY2FlYzg0MmZlNmNlMjU6MHhhN2MxOTBmYThlYmU4NzM2&rp=ELaO-vWon-TgpwEQto769aif5OCnATgCQABIAQ&ictx=1Traceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 103, in getBookingDetails
    driver = webdriver.Firefox(executable_path=geckodriver, options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 412, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
ProtocolError: ('Connection aborted.', BadStatusLine("''",))


https://www.google.com/travel/hotels/entity/CgsIto769aif5OCnARAB/prices?g2lb=2502548,4258168,4260007,4270442,4274032,4291318,4305595,4306835,4308216,4308226,4314846,4317915,4322166,4326765,4328159,4329288,4330113,4330172,4341278,4347918,4270859,4284970,4291517,4316256&hl=en&gl=my&un=1&grf=EmQKLAgOEigSJnIkKiIKBwjkDxAEGAQSBwjkDxAEGAUgADAeQMoCSgcI5A8QAhgcCjQIDBIwEi6yASsSKQonCiUweDMxY2FlYzg0MmZlNmNlMjU6MHhhN2MxOTBmYThlYmU4NzM2&rp=ELaO-vWon-TgpwEQto769aif5OCnATgCQABIAQ&ictx=1Traceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 103, in getBookingDetails
    driver = webdriver.Firefox(executable_path=geckodriver, options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service /home/yo2/303/PYTHON/geckodriver unexpectedly exited. Status code was: -6



https://www.google.com/travel/hotels/entity/CgsIto769aif5OCnARAB/prices?g2lb=2502548,4258168,4260007,4270442,4274032,4291318,4305595,4306835,4308216,4314846,4317915,4326765,4328159,4329288,4330113,4339687,4341278,4347918,4351598,4270859,4284970,4291517,4316256,4356899&hl=en&gl=my&un=1&grf=EmQKLAgOEigSJnIkKiIKBwjkDxADGAQSBwjkDxADGAUgADAeQMoCSgcI5A8QAxgCCjQIDBIwEi6yASsSKQonCiUweDMxY2FlYzg0MmZlNmNlMjU6MHhhN2MxOTBmYThlYmU4NzM2&rp=ELaO-vWon-TgpwE4AkAASAE&ictx=1Traceback (most recent call last):
  File "/home/yo2/303/PYTHON/hotel_bookingdetails/hotel_bookingdetails/hotel_bookingdetails/spiders/bookingdetails.py", line 103, in getBookingDetails
    driver = webdriver.Firefox(executable_path=geckodriver, options=options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: connection refused

